'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ResourceEs
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApp2.ResourceEs", GetType(ResourceEs).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a High.
        '''</summary>
        Friend Shared ReadOnly Property Alt() As String
            Get
                Return ResourceManager.GetString("Alt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Low.
        '''</summary>
        Friend Shared ReadOnly Property Baix() As String
            Get
                Return ResourceManager.GetString("Baix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Good.
        '''</summary>
        Friend Shared ReadOnly Property be() As String
            Get
                Return ResourceManager.GetString("be", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Log in.
        '''</summary>
        Friend Shared ReadOnly Property bt_iniciar() As String
            Get
                Return ResourceManager.GetString("bt_iniciar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sign in.
        '''</summary>
        Friend Shared ReadOnly Property bt_Registrar() As String
            Get
                Return ResourceManager.GetString("bt_Registrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sign in.
        '''</summary>
        Friend Shared ReadOnly Property bt_Registrar2() As String
            Get
                Return ResourceManager.GetString("bt_Registrar2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Last name:.
        '''</summary>
        Friend Shared ReadOnly Property cognomI() As String
            Get
                Return ResourceManager.GetString("cognomI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Resume.
        '''</summary>
        Friend Shared ReadOnly Property curricuI() As String
            Get
                Return ResourceManager.GetString("curricuI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Back.
        '''</summary>
        Friend Shared ReadOnly Property darrere() As String
            Get
                Return ResourceManager.GetString("darrere", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Download curriculum.
        '''</summary>
        Friend Shared ReadOnly Property DescarregarCur() As String
            Get
                Return ResourceManager.GetString("DescarregarCur", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DNI:.
        '''</summary>
        Friend Shared ReadOnly Property dniI() As String
            Get
                Return ResourceManager.GetString("dniI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Done.
        '''</summary>
        Friend Shared ReadOnly Property Feta() As String
            Get
                Return ResourceManager.GetString("Feta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Made.
        '''</summary>
        Friend Shared ReadOnly Property Fetes() As String
            Get
                Return ResourceManager.GetString("Fetes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Create.
        '''</summary>
        Friend Shared ReadOnly Property Guardar() As String
            Get
                Return ResourceManager.GetString("Guardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Drop out.
        '''</summary>
        Friend Shared ReadOnly Property label_baixa() As String
            Get
                Return ResourceManager.GetString("label_baixa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Category:.
        '''</summary>
        Friend Shared ReadOnly Property Label_categ2() As String
            Get
                Return ResourceManager.GetString("Label_categ2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Category:.
        '''</summary>
        Friend Shared ReadOnly Property Label_categoria() As String
            Get
                Return ResourceManager.GetString("Label_categoria", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Username:.
        '''</summary>
        Friend Shared ReadOnly Property label_cognom() As String
            Get
                Return ResourceManager.GetString("label_cognom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password:.
        '''</summary>
        Friend Shared ReadOnly Property label_contra() As String
            Get
                Return ResourceManager.GetString("label_contra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description:.
        '''</summary>
        Friend Shared ReadOnly Property Label_desc2() As String
            Get
                Return ResourceManager.GetString("Label_desc2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description:.
        '''</summary>
        Friend Shared ReadOnly Property label_descr() As String
            Get
                Return ResourceManager.GetString("label_descr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DNI:.
        '''</summary>
        Friend Shared ReadOnly Property label_dni() As String
            Get
                Return ResourceManager.GetString("label_dni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Incidents:.
        '''</summary>
        Friend Shared ReadOnly Property Label_Incid() As String
            Get
                Return ResourceManager.GetString("Label_Incid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Computer specialist:.
        '''</summary>
        Friend Shared ReadOnly Property Label_informatic() As String
            Get
                Return ResourceManager.GetString("Label_informatic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name:.
        '''</summary>
        Friend Shared ReadOnly Property label_nom() As String
            Get
                Return ResourceManager.GetString("label_nom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Population:.
        '''</summary>
        Friend Shared ReadOnly Property label_Poblacio() As String
            Get
                Return ResourceManager.GetString("label_Poblacio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Province:.
        '''</summary>
        Friend Shared ReadOnly Property label_Provincia() As String
            Get
                Return ResourceManager.GetString("label_Provincia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Title:.
        '''</summary>
        Friend Shared ReadOnly Property label_tit2() As String
            Get
                Return ResourceManager.GetString("label_tit2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Title:.
        '''</summary>
        Friend Shared ReadOnly Property Label_titol() As String
            Get
                Return ResourceManager.GetString("Label_titol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select language.
        '''</summary>
        Friend Shared ReadOnly Property Label1_selec_idioma() As String
            Get
                Return ResourceManager.GetString("Label1_selec_idioma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User:.
        '''</summary>
        Friend Shared ReadOnly Property Label1_usuario() As String
            Get
                Return ResourceManager.GetString("Label1_usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Level:.
        '''</summary>
        Friend Shared ReadOnly Property LabelNievell() As String
            Get
                Return ResourceManager.GetString("LabelNievell", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Assessment:.
        '''</summary>
        Friend Shared ReadOnly Property lavel_valoracio() As String
            Get
                Return ResourceManager.GetString("lavel_valoracio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Bad.
        '''</summary>
        Friend Shared ReadOnly Property mal() As String
            Get
                Return ResourceManager.GetString("mal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Medium.
        '''</summary>
        Friend Shared ReadOnly Property Mitja() As String
            Get
                Return ResourceManager.GetString("Mitja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Username:.
        '''</summary>
        Friend Shared ReadOnly Property nom_usuari() As String
            Get
                Return ResourceManager.GetString("nom_usuari", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name:.
        '''</summary>
        Friend Shared ReadOnly Property nomI() As String
            Get
                Return ResourceManager.GetString("nomI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Incidence Not assigned.
        '''</summary>
        Friend Shared ReadOnly Property NomInformatic() As String
            Get
                Return ResourceManager.GetString("NomInformatic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password:.
        '''</summary>
        Friend Shared ReadOnly Property passI() As String
            Get
                Return ResourceManager.GetString("passI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Population:.
        '''</summary>
        Friend Shared ReadOnly Property pobI() As String
            Get
                Return ResourceManager.GetString("pobI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Province:.
        '''</summary>
        Friend Shared ReadOnly Property provinI() As String
            Get
                Return ResourceManager.GetString("provinI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Regular.
        '''</summary>
        Friend Shared ReadOnly Property regular() As String
            Get
                Return ResourceManager.GetString("regular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Yes.
        '''</summary>
        Friend Shared ReadOnly Property Si() As String
            Get
                Return ResourceManager.GetString("Si", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Exit.
        '''</summary>
        Friend Shared ReadOnly Property sortir() As String
            Get
                Return ResourceManager.GetString("sortir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a d.
        '''</summary>
        Friend Shared ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User:.
        '''</summary>
        Friend Shared ReadOnly Property userI() As String
            Get
                Return ResourceManager.GetString("userI", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
